### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript:

### ISSUE THREAD

**Issue by naddika** [dittofeed/dittofeed#506]
```
% git pull ...
% yarn install
% yarn run admin
dittofeed/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/cli.ts:157:44 - error TS7006: Parameter 'pTx' implicitly has an 'any' type.

157         await prisma().$transaction(async (pTx) => {
                                               ~~~
src/cli.ts:160:39 - error TS7006: Parameter 'emailProvider' implicitly has an 'any' type.

160             emailProviders.map(async (emailProvider) => {
                                          ~~~~~~~~~~~~~
src/cli.ts:201:31 - error TS7006: Parameter 'emailTemplate' implicitly has an 'any' type.

201           emailTemplates.map((emailTemplate) => {
                                  ~~~~~~~~~~~~~

    at createTSError (dittofeed/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (dittofeed/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (dittofeed/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (dittofeed/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (dittofeed/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (dittofeed/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  diagnosticCodes: [ 7006, 7006, 7006 ]
}
```

**Comment by maxgurewitz** [comment]
Hi @naddika did you run the `dev-setup.sh` script?

**Comment by maxgurewitz** [comment]
Haven't been able to reproduce this. If anyone can, please reach out! If no one responds in a few weeks I'll close this.
