### ISSUE TITLE
Issue running bootstrap on self-hosted (docker compose)

### ISSUE THREAD

**Issue by edhemphill** [dittofeed/dittofeed#529]
While following the [instructions](https://docs.dittofeed.com/deployment/self-hosted/docker-compose) for docker installation, I am getting an error:

```
$ ./scripts/admin.sh bootstrap --workspace-name="Our Name"
[04:57:37 UTC] INFO: Upserting workspace.
...
[04:57:38 UTC] INFO: creating write key
...
[04:57:38 UTC] INFO: Bootstrapping worker.
[04:57:48 UTC] ERROR: Failed to bootstrap worker.
    err: {
      "type": "Error",
      "message": "Failed to connect before the deadline",
      "stack":
          Error: Failed to connect before the deadline
              at checkState (/service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/client.ts:176:18)
              at Timeout._onTimeout (/service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/channel.ts:745:9)
              at listOnTimeout (node:internal/timers:564:17)
              at processTimers (node:internal/timers:507:7)
    }
```
Everything prior in the script seems to have gone fine.

These are the running containers at the time:
```
$ docker ps
CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS        PORTS                                                                                                                             NAMES
8932c7714910   dittofeed/dittofeed-dashboard:v0.7.4            "docker-entrypoint.s…"   12 hours ago   Up 12 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                         dittofeed-install-dashboard-1
b5134cb6689d   dittofeed/dittofeed-api:v0.7.4                  "docker-entrypoint.s…"   12 hours ago   Up 12 hours   0.0.0.0:3001->3001/tcp, :::3001->3001/tcp                                                                                         dittofeed-install-api-1
8cb6f42b84ae   dittofeed/dittofeed-admin-cli:v0.7.4            "tail -f /dev/null"      12 hours ago   Up 12 hours                                                                                                                                     dittofeed-install-admin-cli-1
236562f2c454   postgres:15                                     "docker-entrypoint.s…"   12 hours ago   Up 12 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                         dittofeed-install-postgres-1
a5abfded5ba2   clickhouse/clickhouse-server:22.9.5.25-alpine   "/entrypoint.sh"         12 hours ago   Up 12 hours   0.0.0.0:8123->8123/tcp, :::8123->8123/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:9009->9009/tcp, :::9009->9009/tcp   dittofeed-install-clickhouse-server-1
```

I checked the logs of these and nothing pops up as an error.

Any ideas?

Thanks!

**Comment by maxgurewitz** [comment]
He @edhemphill, welcome! Yes, both your error logs and the `docker ps` output suggest that the temporal server, labeled as `temporal` in the docker compose file, is not running!

**Comment by edhemphill** [comment]
Thanks so much!

that helped me track down the issue.

**Comment by maxgurewitz** [comment]
Glad!
